### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by joramot** [SergioPeralta22/Awesome-Books#4]
Sergio did a great job, congratulations.

- We suggest that when displaying the form the input fields are not filled with data from local storage.

**Comment by mdg0410** [comment]
Hi @SergioPeralta22 

You have done an excellent job, however, I kindly suggest you consider using `new Date().toDateString();`

This way you will optimize your code, check the documentation if you want to change the output format.

Happy coding
